const COMMISSION_RATE = 0.06;
const SECURITY_CHARGES_RATE = 0.06;
const COMBINED_COMMISSION_AND_SECURITY_RATE =
  COMMISSION_RATE + SECURITY_CHARGES_RATE;
const DEFAULT_POSTAGE = 0;

export {
  COMMISSION_RATE,
  SECURITY_CHARGES_RATE,
  COMBINED_COMMISSION_AND_SECURITY_RATE,
  DEFAULT_POSTAGE,
};
